### ISSUE TITLE
Xcode 6.4 Support

### ISSUE THREAD

**Issue by Prince2k3** [supermarin/Alcatraz#307] opened 2015-06-30 17:29 UTC
Xcode 6.4 is out and Alcatraz doesn't work for it. :/

**Comment by hgonzalez94** [comment] 2015-06-30 19:15
+1 this

**Comment by patricks** [comment] 2015-06-30 20:34
+1

**Comment by Jaym3s** [comment] 2015-06-30 20:44
+1 this is a potential duplicate of https://github.com/supermarin/Alcatraz/issues/294

**Comment by Jaym3s** [comment] 2015-06-30 21:00
fixed for me with
```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`
```

**Comment by cydavy** [comment] 2015-06-30 23:19
@Jaym3s Worked for me too! Thanks! 
I did not need to uninstall Alcatraz or the plugins.

**Comment by njection** [comment] 2015-06-30 23:20
@jaym3s Worked for me too.

**Comment by stevenbaker** [comment] 2015-07-01 00:20
@Jaym3s FTW!  The 'find' one-liner that you provided worked.  Thanks!  :beer:

**Comment by congsun** [comment] 2015-07-01 00:52
@Jaym3s You rock!

**Comment by Prince2k3** [comment] 2015-07-01 01:05
@Jaym3s This works!

**Comment by ajfigueroa** [comment] 2015-07-01 03:28
@Jaym3s Sweet. Thanks!

Anybody having an issue with not being able to find "Package Manager" under "Window" anymore though?

![image](https://cloud.githubusercontent.com/assets/3321592/8446991/bb5c62aa-1f7f-11e5-8200-5b37a076a2fd.png)

**Comment by moshenglei** [comment] 2015-07-01 04:16
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add 'defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID'

it works ,thx

**Comment by alkozin** [comment] 2015-07-01 05:29
We should find smarter solution. This kind of issues is most popular for Alcatraz.

**Comment by gump88** [comment] 2015-07-01 05:50
@Jaym3s thx!

**Comment by sabiland** [comment] 2015-07-01 07:55
@Jaym3s bingo! :)

**Comment by gerald-coddut** [comment] 2015-07-01 07:58
@Jaym3s what a beast that one-liner in Terminal. Made my day!

**Comment by patricks** [comment] 2015-07-01 08:04
@Jaym3s thx!

**Comment by Domsou** [comment] 2015-07-01 08:55
@ajfigueroa 
Same problem here. I quit both Xcode and Simulator and it is solved now.

**Comment by haitham-aboshahba-sociomantic** [comment] 2015-07-01 09:28
@Jaym3s Thanks, works!

**Comment by marioacarvalho** [comment] 2015-07-01 11:07
@ajfigueroa Have you found "Package Manager" under "Window" already? Plugins are working but I can't find the Package Manager..

**Comment by HeroWit** [comment] 2015-07-01 13:01
谢谢，Thanks from China！

**Comment by wilferrel** [comment] 2015-07-01 14:41
@Jaym3s worked for me too you are genius thanks!!

**Closed** 2015-07-01 16:23 UTC

**Comment by ajfigueroa** [comment] 2015-07-01 20:59
@marioacarvalho No dice yet. I've even re-installed and restarted after seeing #308 closed this issue. Any luck on your end?

**Comment by xilin** [comment] 2015-07-02 08:01
@Jaym3s It works again. Thanks!

**Comment by marioacarvalho** [comment] 2015-07-02 09:28
@ajfigueroa Not yet....

**Comment by xclidongbo** [comment] 2015-07-02 22:37
@Jaym3s  It doesn`t work...

**Comment by xclidongbo** [comment] 2015-07-02 22:49
@ajfigueroa I have the same problem with you.

**Comment by supermarin** [comment] 2015-07-02 23:03
Which OSX are you guys running, Yosemite or El Capitan?

**Comment by xclidongbo** [comment] 2015-07-03 00:09
Yosemite

**Comment by xclidongbo** [comment] 2015-07-03 06:36
@supermarin  @ajfigueroa  @Jaym3s

**Comment by richardshergold** [comment] 2015-07-03 07:34
Yosemtite for me.  I've tried all of the above but I still get "Xcode Command Line Tools are not currently installed, and are required to run Alcatraz" after I install and try to access Package Manager.

**Comment by ZakiHo** [comment] 2015-07-03 15:36
+1

**Comment by gantrim** [comment] 2015-07-03 20:20
Not sure if its the case for you guys, but apparently after upgrading to 6.4 it asks if you want to load bundles again. I clicked skip without looking and that was blocking alcatraz from showing up in Window -> Package Manager. Long story short run this:
```
defaults read com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.4
```
to see if Alcatraz is on the skipped list:
```
{
    allowed =     {
        "io.realm.RealmPlugin" =         {
            version = 1;
        };
    };
    skipped =     {
        "com.mneorr.Alcatraz" =         {
            version = 1;
        };
        "io.github.FuzzyAutocomplete" =         {
            version = "2.1.0";
        };
    };
}
```
If it is you can run:
```
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.4
```

and the next time you open xcode it should prompt to load bundles again. Hopefully this helps someone. Original instructions found [here](http://pablin.org/2015/05/27/re-enable-alcatraz-on-xcode-6-dot-3-2-or-newer/)

**Comment by rciobanu-omnifone** [comment] 2015-08-07 09:35
@gantrim So it was installed all along, but just not loaded. Thanks! that worked for me.

**Comment by guillaume-algis** [comment] 2015-08-07 10:23
@supermarin PR #315 would solve this problem.

**Comment by arctouch-diegosantiviago** [comment] 2015-08-18 14:39
"defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.4" on terminal worked for me.

**Comment by dimacheverda** [comment] 2015-09-10 09:27
@arctouch-diegosantiviago that worked for me too, thanks.

**Comment by gebeleysis** [comment] 2015-10-05 11:12
@gantrim Thanks again, this helped me migrate to Xcode 7 also!
