### ISSUE TITLE
Screenshots mix up

### ISSUE THREAD

**Issue by dev4dev** [supermarin/Alcatraz#240] opened 2015-03-19 06:55 UTC
![screen shot 2015-03-19 at 08 51 32](https://cloud.githubusercontent.com/assets/722407/6725663/55ede094-ce15-11e4-9199-c562c432b6a6.png)
If you scroll list quick enough, you can get wrong screenshot loaded in presented cells.
As I can understand, when images loading, they capture cells instead of NSIndexPath...or not. Anyway, here is bug :)

p.s. I see your #239, but this happens even without filtering

**Comment by jurre** [comment] 2015-03-19 06:58
Duplicate of #239 ?

**Comment by dev4dev** [comment] 2015-03-19 07:11
@jurre I think the source of problem is the same, but in this case there is different condition

**Comment by supermarin** [comment] 2015-03-19 23:44
Yep, i'll close it as a dupe

**Closed by supermarin** 2015-03-19 23:44 UTC
