### ISSUE TITLE
UI Alignment Issue with "All / Installed" Button

### ISSUE THREAD

**Issue by mralexgray** [supermarin/Alcatraz#337] opened 2015-08-14 17:04 UTC
This is what I see on a spanking fresh install via the install script in Xcode 7.b3.

![screen shot 2015-08-14 at 12 59 18 pm](https://cloud.githubusercontent.com/assets/262517/9279319/b74f3976-4284-11e5-9e43-1e0f69156a99.png)

The focus ring isn't lining up correctly, as well, although clicking toward the right of the focus ring does activate the "Installed" pane.  Resizing the window (bigger) does NOT seem to help the issue.

**Comment by guillaume-algis** [comment] 2015-08-14 17:26
Duplicate of #226.
Solved in PR #313.

**Closed** 2015-08-17 23:40 UTC
