### ISSUE TITLE
Perhaps `xcodebuild clean` should run before `xcodebuild`

### ISSUE THREAD

**Issue by pdcgomes** [supermarin/Alcatraz#250] opened 2015-04-02 10:12 UTC
Hey guys,

I've been seeing a weird issue when installing [XCActionBar](https://github.com/pdcgomes/XCActionBar) via Alcatraz where the build process will fail to copy over the required nib files.

I doesn't seem like you run `xcodebuild clean` before re-building the project, and doing so seems to solve the issues I'm seeing - wouldn't it make sense to add that step? Any particular reason why you're not going it?

Thanks.

**Comment by benoitsan** [comment] 2015-04-12 15:05
Hi,

 have the same issue with my plugin [BBUncrustifyPlugin](https://github.com/benoitsan/BBUncrustifyPlugin-Xcode).

Steps to reproduce the issue:
1. Build the plugin from the sources.
2. The xib should be copied as expected: `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/UncrustifyPlugin.xcplugin/Contents/Resources/XCFPreferencesWindowController.nib`
3. Remove the plugin in Alcatraz.
4. Reinstall the plugin in Alcatraz.
5. The xib file is now missing.
6. If I build again the plugin from the sources, the xib is no more copied. I need to peform a "Clean Build Folder" in Xcode in order to see the xib copied correctly.

As @pdcgomes said, I think that cleaning is needed because Xcode fails to do the incremental copy.

**Comment by supermarin** [comment] 2015-05-22 18:05
Fixed in #261

**Closed** 2015-05-22 18:05 UTC
